// AUTO-GENERATED by .claude/skills/sync-types — do not edit by hand.
// Re-run: ask Claude to "sync types" after applying a migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      accounting_invoices: {
        Row: {
          amount: number
          created_at: string
          created_by: string | null
          currency: string
          direction: string
          due_date: string | null
          id: string
          invoice_no: string
          issued_date: string
          notes: string | null
          paid_at: string | null
          party_name: string
          status: string
          updated_at: string
        }
        Insert: {
          amount: number
          created_at?: string
          created_by?: string | null
          currency?: string
          direction: string
          due_date?: string | null
          id?: string
          invoice_no: string
          issued_date: string
          notes?: string | null
          paid_at?: string | null
          party_name: string
          status?: string
          updated_at?: string
        }
        Update: {
          amount?: number
          created_at?: string
          created_by?: string | null
          currency?: string
          direction?: string
          due_date?: string | null
          id?: string
          invoice_no?: string
          issued_date?: string
          notes?: string | null
          paid_at?: string | null
          party_name?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      activity_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          payload: Json
          task_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          task_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          task_id?: string
        }
        Relationships: []
      }
      departments: {
        Row: {
          created_at: string
          description: string | null
          head_user_id: string | null
          id: string
          name: string
          updated_at: string
          workspace_id: string | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          head_user_id?: string | null
          id?: string
          name: string
          updated_at?: string
          workspace_id?: string | null
        }
        Update: {
          created_at?: string
          description?: string | null
          head_user_id?: string | null
          id?: string
          name?: string
          updated_at?: string
          workspace_id?: string | null
        }
        Relationships: []
      }
      files: {
        Row: {
          bucket: string
          checksum: string | null
          comment_id: string | null
          created_at: string
          customer_id: string | null
          deleted_at: string | null
          filename: string
          finalized_at: string | null
          id: string
          invoice_id: string | null
          mime_type: string
          owner_id: string | null
          path: string
          product_id: string | null
          size_bytes: number
          task_id: string | null
        }
        Insert: {
          bucket: string
          checksum?: string | null
          comment_id?: string | null
          created_at?: string
          customer_id?: string | null
          deleted_at?: string | null
          filename: string
          finalized_at?: string | null
          id?: string
          invoice_id?: string | null
          mime_type: string
          owner_id?: string | null
          path: string
          product_id?: string | null
          size_bytes: number
          task_id?: string | null
        }
        Update: {
          bucket?: string
          checksum?: string | null
          comment_id?: string | null
          created_at?: string
          customer_id?: string | null
          deleted_at?: string | null
          filename?: string
          finalized_at?: string | null
          id?: string
          invoice_id?: string | null
          mime_type?: string
          owner_id?: string | null
          path?: string
          product_id?: string | null
          size_bytes?: number
          task_id?: string | null
        }
        Relationships: []
      }
      hr_leave_requests: {
        Row: {
          approved_at: string | null
          approver_id: string | null
          approver_note: string | null
          created_at: string
          days_count: number
          from_date: string
          id: string
          leave_type: string
          reason: string | null
          status: string
          to_date: string
          updated_at: string
          user_id: string
        }
        Insert: {
          approved_at?: string | null
          approver_id?: string | null
          approver_note?: string | null
          created_at?: string
          days_count: number
          from_date: string
          id?: string
          leave_type?: string
          reason?: string | null
          status?: string
          to_date: string
          updated_at?: string
          user_id: string
        }
        Update: {
          approved_at?: string | null
          approver_id?: string | null
          approver_note?: string | null
          created_at?: string
          days_count?: number
          from_date?: string
          id?: string
          leave_type?: string
          reason?: string | null
          status?: string
          to_date?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          actor_id: string | null
          created_at: string
          id: string
          payload: Json
          read_at: string | null
          task_id: string | null
          type: string
          user_id: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          read_at?: string | null
          task_id?: string | null
          type: string
          user_id: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          read_at?: string | null
          task_id?: string | null
          type?: string
          user_id?: string
        }
        Relationships: []
      }
      sales_customers: {
        Row: {
          address: string | null
          code: string | null
          created_at: string
          email: string | null
          id: string
          is_active: boolean
          name: string
          notes: string | null
          owner_id: string | null
          phone: string | null
          updated_at: string
        }
        Insert: {
          address?: string | null
          code?: string | null
          created_at?: string
          email?: string | null
          id?: string
          is_active?: boolean
          name: string
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          updated_at?: string
        }
        Update: {
          address?: string | null
          code?: string | null
          created_at?: string
          email?: string | null
          id?: string
          is_active?: boolean
          name?: string
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      warehouse_materials: {
        Row: {
          code: string
          created_at: string
          group_name: string | null
          id: string
          is_active: boolean
          min_stock: number
          name: string
          note: string | null
          shelf_location: string | null
          unit: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          group_name?: string | null
          id?: string
          is_active?: boolean
          min_stock?: number
          name: string
          note?: string | null
          shelf_location?: string | null
          unit?: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          group_name?: string | null
          id?: string
          is_active?: boolean
          min_stock?: number
          name?: string
          note?: string | null
          shelf_location?: string | null
          unit?: string
          updated_at?: string
        }
        Relationships: []
      }
      warehouse_movements: {
        Row: {
          created_at: string
          created_by: string | null
          direction: string
          id: string
          material_id: string
          note: string | null
          qc_status: string | null
          qty: number
          qty_rejected: number
          ref_no: string | null
          ref_type: string
          shelf_location: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          direction: string
          id?: string
          material_id: string
          note?: string | null
          qc_status?: string | null
          qty: number
          qty_rejected?: number
          ref_no?: string | null
          ref_type: string
          shelf_location?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          direction?: string
          id?: string
          material_id?: string
          note?: string | null
          qc_status?: string | null
          qty?: number
          qty_rejected?: number
          ref_no?: string | null
          ref_type?: string
          shelf_location?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'warehouse_movements_material_id_fkey'
            columns: ['material_id']
            isOneToOne: false
            referencedRelation: 'warehouse_materials'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'warehouse_movements_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
      settings: {
        Row: {
          key: string
          updated_at: string
          value: Json
        }
        Insert: {
          key: string
          updated_at?: string
          value: Json
        }
        Update: {
          key?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      task_comments: {
        Row: {
          body: string
          created_at: string
          id: string
          kind: string
          task_id: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          kind?: string
          task_id: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          kind?: string
          task_id?: string
          user_id?: string
        }
        Relationships: []
      }
      tasks: {
        Row: {
          actual_hours: number | null
          assignee_id: string
          assigner_id: string
          cancelled_at: string | null
          category: string | null
          completed_at: string | null
          created_at: string
          department_id: string | null
          description: string | null
          due_date: string | null
          estimate_hours: number | null
          id: string
          kind: string
          parent_id: string | null
          period_month: string | null
          planned_date: string | null
          priority: string
          progress_percent: number
          started_at: string | null
          status: string
          submitted_at: string | null
          tags: string[]
          task_code: string | null
          title: string
          updated_at: string
        }
        Insert: {
          actual_hours?: number | null
          assignee_id: string
          assigner_id: string
          cancelled_at?: string | null
          category?: string | null
          completed_at?: string | null
          created_at?: string
          department_id?: string | null
          description?: string | null
          due_date?: string | null
          estimate_hours?: number | null
          id?: string
          kind?: string
          parent_id?: string | null
          period_month?: string | null
          planned_date?: string | null
          priority?: string
          progress_percent?: number
          started_at?: string | null
          status?: string
          submitted_at?: string | null
          tags?: string[]
          task_code?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          actual_hours?: number | null
          assignee_id?: string
          assigner_id?: string
          cancelled_at?: string | null
          category?: string | null
          completed_at?: string | null
          created_at?: string
          department_id?: string | null
          description?: string | null
          due_date?: string | null
          estimate_hours?: number | null
          id?: string
          kind?: string
          parent_id?: string | null
          period_month?: string | null
          planned_date?: string | null
          priority?: string
          progress_percent?: number
          started_at?: string | null
          status?: string
          submitted_at?: string | null
          tags?: string[]
          task_code?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      technical_products: {
        Row: {
          bom_url: string | null
          category: string | null
          code: string
          created_at: string
          drawing_url: string | null
          id: string
          is_active: boolean
          name: string
          notes: string | null
          updated_at: string
        }
        Insert: {
          bom_url?: string | null
          category?: string | null
          code: string
          created_at?: string
          drawing_url?: string | null
          id?: string
          is_active?: boolean
          name: string
          notes?: string | null
          updated_at?: string
        }
        Update: {
          bom_url?: string | null
          category?: string | null
          code?: string
          created_at?: string
          drawing_url?: string | null
          id?: string
          is_active?: boolean
          name?: string
          notes?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      user_audit_log: {
        Row: {
          action: string
          actor_id: string | null
          after: Json | null
          before: Json | null
          created_at: string
          id: string
          reason: string | null
          target_user_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          id?: string
          reason?: string | null
          target_user_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          id?: string
          reason?: string | null
          target_user_id?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          deleted_at: string | null
          department_id: string | null
          email: string
          employee_code: string | null
          id: string
          is_active: boolean
          last_login_at: string | null
          name: string | null
          password_changed_at: string | null
          password_hash: string
          role: string
          title: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          department_id?: string | null
          email: string
          employee_code?: string | null
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          name?: string | null
          password_changed_at?: string | null
          password_hash: string
          role?: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          department_id?: string | null
          email?: string
          employee_code?: string | null
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          name?: string | null
          password_changed_at?: string | null
          password_hash?: string
          role?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      v_task_summary: {
        Row: {
          actual_hours: number | null
          assignee_email: string | null
          assignee_id: string | null
          assignee_name: string | null
          assigner_email: string | null
          assigner_id: string | null
          assigner_name: string | null
          cancelled_at: string | null
          category: string | null
          completed_at: string | null
          created_at: string | null
          department_id: string | null
          department_name: string | null
          description: string | null
          due_date: string | null
          estimate_hours: number | null
          id: string | null
          kind: string | null
          parent_id: string | null
          period_month: string | null
          planned_date: string | null
          priority: string | null
          progress_percent: number | null
          started_at: string | null
          status: string | null
          submitted_at: string | null
          tags: string[] | null
          task_code: string | null
          title: string | null
          updated_at: string | null
        }
        Relationships: []
      }
      warehouse_stock: {
        Row: {
          code: string | null
          group_name: string | null
          is_active: boolean | null
          material_id: string | null
          min_stock: number | null
          name: string | null
          on_hand: number | null
          shelf_location: string | null
          unit: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
