// AUTO-GENERATED by .claude/skills/sync-types — do not edit by hand.
// Re-run: ask Claude to "sync types" after applying a migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      accounting_invoices: {
        Row: {
          amount: number
          created_at: string
          created_by: string | null
          currency: string
          direction: string
          due_date: string | null
          id: string
          invoice_no: string
          issued_date: string
          notes: string | null
          paid_at: string | null
          party_name: string
          status: string
          updated_at: string
        }
        Insert: {
          amount: number
          created_at?: string
          created_by?: string | null
          currency?: string
          direction: string
          due_date?: string | null
          id?: string
          invoice_no: string
          issued_date: string
          notes?: string | null
          paid_at?: string | null
          party_name: string
          status?: string
          updated_at?: string
        }
        Update: {
          amount?: number
          created_at?: string
          created_by?: string | null
          currency?: string
          direction?: string
          due_date?: string | null
          id?: string
          invoice_no?: string
          issued_date?: string
          notes?: string | null
          paid_at?: string | null
          party_name?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "accounting_invoices_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      activity_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          payload: Json
          task_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          task_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          task_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "v_task_summary"
            referencedColumns: ["id"]
          },
        ]
      }
      catalog_items: {
        Row: {
          code: string
          created_at: string
          id: string
          is_active: boolean
          label: string
          sort_order: number
          type: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          label: string
          sort_order?: number
          type: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          label?: string
          sort_order?: number
          type?: string
          updated_at?: string
        }
        Relationships: []
      }
      departments: {
        Row: {
          created_at: string
          description: string | null
          head_user_id: string | null
          id: string
          name: string
          updated_at: string
          workspace_id: string | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          head_user_id?: string | null
          id?: string
          name: string
          updated_at?: string
          workspace_id?: string | null
        }
        Update: {
          created_at?: string
          description?: string | null
          head_user_id?: string | null
          id?: string
          name?: string
          updated_at?: string
          workspace_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "departments_head_user_id_fkey"
            columns: ["head_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      doc_counters: {
        Row: {
          kind: string
          last_no: number
          year: number
        }
        Insert: {
          kind: string
          last_no?: number
          year: number
        }
        Update: {
          kind?: string
          last_no?: number
          year?: number
        }
        Relationships: []
      }
      files: {
        Row: {
          bucket: string
          checksum: string | null
          comment_id: string | null
          created_at: string
          customer_id: string | null
          deleted_at: string | null
          filename: string
          finalized_at: string | null
          id: string
          invoice_id: string | null
          mime_type: string
          owner_id: string | null
          path: string
          product_id: string | null
          production_order_id: string | null
          purchase_order_id: string | null
          quote_id: string | null
          sales_order_id: string | null
          size_bytes: number
          task_id: string | null
        }
        Insert: {
          bucket: string
          checksum?: string | null
          comment_id?: string | null
          created_at?: string
          customer_id?: string | null
          deleted_at?: string | null
          filename: string
          finalized_at?: string | null
          id?: string
          invoice_id?: string | null
          mime_type: string
          owner_id?: string | null
          path: string
          product_id?: string | null
          production_order_id?: string | null
          purchase_order_id?: string | null
          quote_id?: string | null
          sales_order_id?: string | null
          size_bytes: number
          task_id?: string | null
        }
        Update: {
          bucket?: string
          checksum?: string | null
          comment_id?: string | null
          created_at?: string
          customer_id?: string | null
          deleted_at?: string | null
          filename?: string
          finalized_at?: string | null
          id?: string
          invoice_id?: string | null
          mime_type?: string
          owner_id?: string | null
          path?: string
          product_id?: string | null
          production_order_id?: string | null
          purchase_order_id?: string | null
          quote_id?: string | null
          sales_order_id?: string | null
          size_bytes?: number
          task_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "files_comment_id_fkey"
            columns: ["comment_id"]
            isOneToOne: false
            referencedRelation: "task_comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sales_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_invoice_id_fkey"
            columns: ["invoice_id"]
            isOneToOne: false
            referencedRelation: "accounting_invoices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "technical_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
          {
            foreignKeyName: "files_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "supply_purchase_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "sales_quotes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_sales_order_id_fkey"
            columns: ["sales_order_id"]
            isOneToOne: false
            referencedRelation: "sales_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_sales_order_id_fkey"
            columns: ["sales_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "files_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "v_task_summary"
            referencedColumns: ["id"]
          },
        ]
      }
      hr_leave_requests: {
        Row: {
          approved_at: string | null
          approver_id: string | null
          approver_note: string | null
          created_at: string
          days_count: number
          from_date: string
          id: string
          leave_type: string
          reason: string | null
          status: string
          to_date: string
          updated_at: string
          user_id: string
        }
        Insert: {
          approved_at?: string | null
          approver_id?: string | null
          approver_note?: string | null
          created_at?: string
          days_count: number
          from_date: string
          id?: string
          leave_type?: string
          reason?: string | null
          status?: string
          to_date: string
          updated_at?: string
          user_id: string
        }
        Update: {
          approved_at?: string | null
          approver_id?: string | null
          approver_note?: string | null
          created_at?: string
          days_count?: number
          from_date?: string
          id?: string
          leave_type?: string
          reason?: string | null
          status?: string
          to_date?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "hr_leave_requests_approver_id_fkey"
            columns: ["approver_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hr_leave_requests_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          actor_id: string | null
          created_at: string
          id: string
          payload: Json
          read_at: string | null
          task_id: string | null
          type: string
          user_id: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          read_at?: string | null
          task_id?: string | null
          type: string
          user_id: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json
          read_at?: string | null
          task_id?: string | null
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "v_task_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      production_order_components: {
        Row: {
          cluster: string | null
          created_at: string
          dm_kg: number | null
          final_stage: string | null
          id: string
          material_id: string | null
          material_type: string | null
          name: string
          note: string | null
          order_line_id: string
          pcs_per_bar: number | null
          production_order_id: string
          qty_per_unit: number
          sort_order: number
          spec_length_mm: number | null
          spec_thickness_mm: number | null
          spec_width_mm: number | null
          updated_at: string
        }
        Insert: {
          cluster?: string | null
          created_at?: string
          dm_kg?: number | null
          final_stage?: string | null
          id?: string
          material_id?: string | null
          material_type?: string | null
          name: string
          note?: string | null
          order_line_id: string
          pcs_per_bar?: number | null
          production_order_id: string
          qty_per_unit: number
          sort_order?: number
          spec_length_mm?: number | null
          spec_thickness_mm?: number | null
          spec_width_mm?: number | null
          updated_at?: string
        }
        Update: {
          cluster?: string | null
          created_at?: string
          dm_kg?: number | null
          final_stage?: string | null
          id?: string
          material_id?: string | null
          material_type?: string | null
          name?: string
          note?: string | null
          order_line_id?: string
          pcs_per_bar?: number | null
          production_order_id?: string
          qty_per_unit?: number
          sort_order?: number
          spec_length_mm?: number | null
          spec_thickness_mm?: number | null
          spec_width_mm?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_order_components_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_order_components_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_stock"
            referencedColumns: ["material_id"]
          },
          {
            foreignKeyName: "production_order_components_order_line_id_fkey"
            columns: ["order_line_id"]
            isOneToOne: false
            referencedRelation: "sales_order_lines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_order_components_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_order_components_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
        ]
      }
      production_order_line_specs: {
        Row: {
          created_at: string
          id: string
          important_note: string | null
          note: string | null
          order_line_id: string
          production_order_id: string
          specs: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          important_note?: string | null
          note?: string | null
          order_line_id: string
          production_order_id: string
          specs?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          important_note?: string | null
          note?: string | null
          order_line_id?: string
          production_order_id?: string
          specs?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_order_line_specs_order_line_id_fkey"
            columns: ["order_line_id"]
            isOneToOne: false
            referencedRelation: "sales_order_lines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_order_line_specs_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_order_line_specs_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
        ]
      }
      production_orders: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          code: string
          completed_at: string | null
          container_summary: string | null
          created_at: string
          current_stage: string | null
          id: string
          issued_at: string | null
          issued_by: string | null
          note: string | null
          received_date: string | null
          rejected_reason: string | null
          sales_order_id: string
          ship_date: string | null
          status: string
          updated_at: string
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          code: string
          completed_at?: string | null
          container_summary?: string | null
          created_at?: string
          current_stage?: string | null
          id?: string
          issued_at?: string | null
          issued_by?: string | null
          note?: string | null
          received_date?: string | null
          rejected_reason?: string | null
          sales_order_id: string
          ship_date?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          code?: string
          completed_at?: string | null
          container_summary?: string | null
          created_at?: string
          current_stage?: string | null
          id?: string
          issued_at?: string | null
          issued_by?: string | null
          note?: string | null
          received_date?: string | null
          rejected_reason?: string | null
          sales_order_id?: string
          ship_date?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_orders_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_orders_issued_by_fkey"
            columns: ["issued_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_orders_sales_order_id_fkey"
            columns: ["sales_order_id"]
            isOneToOne: true
            referencedRelation: "sales_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_orders_sales_order_id_fkey"
            columns: ["sales_order_id"]
            isOneToOne: true
            referencedRelation: "v_order_tracking"
            referencedColumns: ["id"]
          },
        ]
      }
      production_output_entries: {
        Row: {
          component_id: string
          created_at: string
          created_by: string | null
          defect_qty: number
          entry_date: string
          id: string
          kg: number | null
          machine_note: string | null
          note: string | null
          production_order_id: string
          qty: number
          stage: string
          team_department_id: string | null
        }
        Insert: {
          component_id: string
          created_at?: string
          created_by?: string | null
          defect_qty?: number
          entry_date: string
          id?: string
          kg?: number | null
          machine_note?: string | null
          note?: string | null
          production_order_id: string
          qty: number
          stage: string
          team_department_id?: string | null
        }
        Update: {
          component_id?: string
          created_at?: string
          created_by?: string | null
          defect_qty?: number
          entry_date?: string
          id?: string
          kg?: number | null
          machine_note?: string | null
          note?: string | null
          production_order_id?: string
          qty?: number
          stage?: string
          team_department_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "production_output_entries_component_id_fkey"
            columns: ["component_id"]
            isOneToOne: false
            referencedRelation: "production_order_components"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_output_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_output_entries_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_output_entries_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
          {
            foreignKeyName: "production_output_entries_team_department_id_fkey"
            columns: ["team_department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
        ]
      }
      production_outsource_entries: {
        Row: {
          component_id: string
          created_at: string
          created_by: string | null
          defect_qty: number
          direction: string
          entry_date: string
          id: string
          kg: number | null
          note: string | null
          production_order_id: string
          qty: number
          supplier_id: string
        }
        Insert: {
          component_id: string
          created_at?: string
          created_by?: string | null
          defect_qty?: number
          direction: string
          entry_date: string
          id?: string
          kg?: number | null
          note?: string | null
          production_order_id: string
          qty: number
          supplier_id: string
        }
        Update: {
          component_id?: string
          created_at?: string
          created_by?: string | null
          defect_qty?: number
          direction?: string
          entry_date?: string
          id?: string
          kg?: number | null
          note?: string | null
          production_order_id?: string
          qty?: number
          supplier_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "production_outsource_entries_component_id_fkey"
            columns: ["component_id"]
            isOneToOne: false
            referencedRelation: "production_order_components"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_outsource_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_outsource_entries_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_outsource_entries_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
          {
            foreignKeyName: "production_outsource_entries_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "supply_suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      production_progress: {
        Row: {
          action: string
          created_at: string
          id: string
          note: string | null
          production_order_id: string
          stage: string
          updated_by: string | null
        }
        Insert: {
          action?: string
          created_at?: string
          id?: string
          note?: string | null
          production_order_id: string
          stage: string
          updated_by?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          id?: string
          note?: string | null
          production_order_id?: string
          stage?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "production_progress_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "production_progress_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
          {
            foreignKeyName: "production_progress_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_customers: {
        Row: {
          address: string | null
          code: string | null
          contact_person: string | null
          country: string | null
          created_at: string
          default_currency: string | null
          default_payment_terms: string | null
          default_price_term: string | null
          email: string | null
          fax: string | null
          fsc_cert: string | null
          id: string
          is_active: boolean
          name: string
          notes: string | null
          owner_id: string | null
          phone: string | null
          port_of_discharge: string | null
          representative_title: string | null
          tax_code: string | null
          updated_at: string
        }
        Insert: {
          address?: string | null
          code?: string | null
          contact_person?: string | null
          country?: string | null
          created_at?: string
          default_currency?: string | null
          default_payment_terms?: string | null
          default_price_term?: string | null
          email?: string | null
          fax?: string | null
          fsc_cert?: string | null
          id?: string
          is_active?: boolean
          name: string
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          port_of_discharge?: string | null
          representative_title?: string | null
          tax_code?: string | null
          updated_at?: string
        }
        Update: {
          address?: string | null
          code?: string | null
          contact_person?: string | null
          country?: string | null
          created_at?: string
          default_currency?: string | null
          default_payment_terms?: string | null
          default_price_term?: string | null
          email?: string | null
          fax?: string | null
          fsc_cert?: string | null
          id?: string
          is_active?: boolean
          name?: string
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          port_of_discharge?: string | null
          representative_title?: string | null
          tax_code?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_customers_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_order_changes: {
        Row: {
          change: Json
          changed_by: string | null
          created_at: string
          id: string
          note: string | null
          order_id: string
        }
        Insert: {
          change: Json
          changed_by?: string | null
          created_at?: string
          id?: string
          note?: string | null
          order_id: string
        }
        Update: {
          change?: Json
          changed_by?: string | null
          created_at?: string
          id?: string
          note?: string | null
          order_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_order_changes_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_order_changes_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "sales_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_order_changes_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_order_lines: {
        Row: {
          id: string
          note: string | null
          order_id: string
          product_id: string
          qty: number
          sort_order: number
          unit_price: number
        }
        Insert: {
          id?: string
          note?: string | null
          order_id: string
          product_id: string
          qty: number
          sort_order?: number
          unit_price?: number
        }
        Update: {
          id?: string
          note?: string | null
          order_id?: string
          product_id?: string
          qty?: number
          sort_order?: number
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "sales_order_lines_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "sales_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_order_lines_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_order_lines_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "technical_products"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_orders: {
        Row: {
          code: string
          container_summary: string | null
          created_at: string
          created_by: string | null
          currency: string
          customer_id: string
          customer_po_no: string | null
          deposit_percent: number | null
          due_date: string | null
          id: string
          note: string | null
          partial_shipment: boolean | null
          payment_method: string | null
          payment_terms: string | null
          port_of_discharge: string | null
          port_of_loading: string | null
          price_term: string | null
          qty_tolerance_pct: number | null
          quote_id: string | null
          required_docs: string | null
          status: string
          transhipment: boolean | null
          updated_at: string
        }
        Insert: {
          code: string
          container_summary?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string
          customer_id: string
          customer_po_no?: string | null
          deposit_percent?: number | null
          due_date?: string | null
          id?: string
          note?: string | null
          partial_shipment?: boolean | null
          payment_method?: string | null
          payment_terms?: string | null
          port_of_discharge?: string | null
          port_of_loading?: string | null
          price_term?: string | null
          qty_tolerance_pct?: number | null
          quote_id?: string | null
          required_docs?: string | null
          status?: string
          transhipment?: boolean | null
          updated_at?: string
        }
        Update: {
          code?: string
          container_summary?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string
          customer_id?: string
          customer_po_no?: string | null
          deposit_percent?: number | null
          due_date?: string | null
          id?: string
          note?: string | null
          partial_shipment?: boolean | null
          payment_method?: string | null
          payment_terms?: string | null
          port_of_discharge?: string | null
          port_of_loading?: string | null
          price_term?: string | null
          qty_tolerance_pct?: number | null
          quote_id?: string | null
          required_docs?: string | null
          status?: string
          transhipment?: boolean | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sales_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "sales_quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_quote_lines: {
        Row: {
          id: string
          note: string | null
          product_id: string
          qty: number
          quote_id: string
          sort_order: number
          unit_price: number
        }
        Insert: {
          id?: string
          note?: string | null
          product_id: string
          qty: number
          quote_id: string
          sort_order?: number
          unit_price?: number
        }
        Update: {
          id?: string
          note?: string | null
          product_id?: string
          qty?: number
          quote_id?: string
          sort_order?: number
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "sales_quote_lines_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "technical_products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_quote_lines_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "sales_quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_quotes: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          code: string
          created_at: string
          created_by: string | null
          currency: string
          customer_id: string
          id: string
          note: string | null
          payment_terms: string | null
          price_term: string | null
          rejected_reason: string | null
          status: string
          updated_at: string
          valid_from: string | null
          valid_to: string | null
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          code: string
          created_at?: string
          created_by?: string | null
          currency?: string
          customer_id: string
          id?: string
          note?: string | null
          payment_terms?: string | null
          price_term?: string | null
          rejected_reason?: string | null
          status?: string
          updated_at?: string
          valid_from?: string | null
          valid_to?: string | null
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          code?: string
          created_at?: string
          created_by?: string | null
          currency?: string
          customer_id?: string
          id?: string
          note?: string | null
          payment_terms?: string | null
          price_term?: string | null
          rejected_reason?: string | null
          status?: string
          updated_at?: string
          valid_from?: string | null
          valid_to?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sales_quotes_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_quotes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_quotes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sales_customers"
            referencedColumns: ["id"]
          },
        ]
      }
      settings: {
        Row: {
          key: string
          updated_at: string
          value: Json
        }
        Insert: {
          key: string
          updated_at?: string
          value: Json
        }
        Update: {
          key?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      supply_purchase_order_lines: {
        Row: {
          id: string
          material_id: string
          note: string | null
          po_id: string
          qty_ordered: number
          qty2: number | null
          sort_order: number
          spec: string | null
          unit_price: number | null
          unit2: string | null
        }
        Insert: {
          id?: string
          material_id: string
          note?: string | null
          po_id: string
          qty_ordered: number
          qty2?: number | null
          sort_order?: number
          spec?: string | null
          unit_price?: number | null
          unit2?: string | null
        }
        Update: {
          id?: string
          material_id?: string
          note?: string | null
          po_id?: string
          qty_ordered?: number
          qty2?: number | null
          sort_order?: number
          spec?: string | null
          unit_price?: number | null
          unit2?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "supply_purchase_order_lines_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchase_order_lines_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_stock"
            referencedColumns: ["material_id"]
          },
          {
            foreignKeyName: "supply_purchase_order_lines_po_id_fkey"
            columns: ["po_id"]
            isOneToOne: false
            referencedRelation: "supply_purchase_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      supply_purchase_orders: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          code: string
          created_at: string
          created_by: string | null
          currency: string
          expected_at: string | null
          id: string
          note: string | null
          ordered_at: string | null
          price_includes_vat: boolean
          production_order_id: string
          status: string
          supplier_id: string
          terms: string | null
          updated_at: string
          vat_rate: number | null
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          code: string
          created_at?: string
          created_by?: string | null
          currency?: string
          expected_at?: string | null
          id?: string
          note?: string | null
          ordered_at?: string | null
          price_includes_vat?: boolean
          production_order_id: string
          status?: string
          supplier_id: string
          terms?: string | null
          updated_at?: string
          vat_rate?: number | null
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          code?: string
          created_at?: string
          created_by?: string | null
          currency?: string
          expected_at?: string | null
          id?: string
          note?: string | null
          ordered_at?: string | null
          price_includes_vat?: boolean
          production_order_id?: string
          status?: string
          supplier_id?: string
          terms?: string | null
          updated_at?: string
          vat_rate?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "supply_purchase_orders_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchase_orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchase_orders_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchase_orders_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
          {
            foreignKeyName: "supply_purchase_orders_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "supply_suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      supply_supplier_prices: {
        Row: {
          created_at: string
          created_by: string | null
          currency: string
          id: string
          material_id: string
          note: string | null
          price: number
          supplier_id: string
          updated_at: string
          valid_from: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          currency?: string
          id?: string
          material_id: string
          note?: string | null
          price: number
          supplier_id: string
          updated_at?: string
          valid_from?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          currency?: string
          id?: string
          material_id?: string
          note?: string | null
          price?: number
          supplier_id?: string
          updated_at?: string
          valid_from?: string
        }
        Relationships: [
          {
            foreignKeyName: "supply_supplier_prices_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_supplier_prices_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_supplier_prices_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_stock"
            referencedColumns: ["material_id"]
          },
          {
            foreignKeyName: "supply_supplier_prices_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "supply_suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      supply_suppliers: {
        Row: {
          address: string | null
          bank_account: string | null
          bank_name: string | null
          business_license: string | null
          buyer_id: string | null
          can_order: boolean
          code: string | null
          company_name: string | null
          country: string | null
          created_at: string
          created_by: string | null
          currency: string | null
          delivery_method: string | null
          email: string | null
          founded_on: string | null
          id: string
          import_export: string | null
          incoterms: string | null
          invoice_terms: string | null
          is_active: boolean
          lead_time_days: number | null
          legal_rep: string | null
          lock_reason: string | null
          moq: string | null
          name: string
          note: string | null
          payment_terms: string | null
          phone: string | null
          priority: string | null
          rating: string | null
          region: string | null
          registered_address: string | null
          return_policy: string | null
          short_name: string | null
          status: string
          swift_code: string | null
          tax_no: string | null
          trading_address: string | null
          type: string | null
          updated_at: string
          updated_by: string | null
          warehouse_address: string | null
          warranty_policy: string | null
          website: string | null
        }
        Insert: {
          address?: string | null
          bank_account?: string | null
          bank_name?: string | null
          business_license?: string | null
          buyer_id?: string | null
          can_order?: boolean
          code?: string | null
          company_name?: string | null
          country?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string | null
          delivery_method?: string | null
          email?: string | null
          founded_on?: string | null
          id?: string
          import_export?: string | null
          incoterms?: string | null
          invoice_terms?: string | null
          is_active?: boolean
          lead_time_days?: number | null
          legal_rep?: string | null
          lock_reason?: string | null
          moq?: string | null
          name: string
          note?: string | null
          payment_terms?: string | null
          phone?: string | null
          priority?: string | null
          rating?: string | null
          region?: string | null
          registered_address?: string | null
          return_policy?: string | null
          short_name?: string | null
          status?: string
          swift_code?: string | null
          tax_no?: string | null
          trading_address?: string | null
          type?: string | null
          updated_at?: string
          updated_by?: string | null
          warehouse_address?: string | null
          warranty_policy?: string | null
          website?: string | null
        }
        Update: {
          address?: string | null
          bank_account?: string | null
          bank_name?: string | null
          business_license?: string | null
          buyer_id?: string | null
          can_order?: boolean
          code?: string | null
          company_name?: string | null
          country?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string | null
          delivery_method?: string | null
          email?: string | null
          founded_on?: string | null
          id?: string
          import_export?: string | null
          incoterms?: string | null
          invoice_terms?: string | null
          is_active?: boolean
          lead_time_days?: number | null
          legal_rep?: string | null
          lock_reason?: string | null
          moq?: string | null
          name?: string
          note?: string | null
          payment_terms?: string | null
          phone?: string | null
          priority?: string | null
          rating?: string | null
          region?: string | null
          registered_address?: string | null
          return_policy?: string | null
          short_name?: string | null
          status?: string
          swift_code?: string | null
          tax_no?: string | null
          trading_address?: string | null
          type?: string | null
          updated_at?: string
          updated_by?: string | null
          warehouse_address?: string | null
          warranty_policy?: string | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "supply_suppliers_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_suppliers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_suppliers_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      task_comments: {
        Row: {
          body: string
          created_at: string
          id: string
          kind: string
          task_id: string
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          kind?: string
          task_id: string
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          kind?: string
          task_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_comments_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_comments_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "v_task_summary"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_comments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          actual_hours: number | null
          assignee_id: string
          assigner_id: string
          cancelled_at: string | null
          category: string | null
          completed_at: string | null
          created_at: string
          department_id: string | null
          description: string | null
          due_date: string | null
          estimate_hours: number | null
          id: string
          kind: string
          parent_id: string | null
          period_month: string | null
          planned_date: string | null
          priority: string
          progress_percent: number
          started_at: string | null
          status: string
          submitted_at: string | null
          tags: string[]
          task_code: string | null
          title: string
          updated_at: string
        }
        Insert: {
          actual_hours?: number | null
          assignee_id: string
          assigner_id: string
          cancelled_at?: string | null
          category?: string | null
          completed_at?: string | null
          created_at?: string
          department_id?: string | null
          description?: string | null
          due_date?: string | null
          estimate_hours?: number | null
          id?: string
          kind?: string
          parent_id?: string | null
          period_month?: string | null
          planned_date?: string | null
          priority?: string
          progress_percent?: number
          started_at?: string | null
          status?: string
          submitted_at?: string | null
          tags?: string[]
          task_code?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          actual_hours?: number | null
          assignee_id?: string
          assigner_id?: string
          cancelled_at?: string | null
          category?: string | null
          completed_at?: string | null
          created_at?: string
          department_id?: string | null
          description?: string | null
          due_date?: string | null
          estimate_hours?: number | null
          id?: string
          kind?: string
          parent_id?: string | null
          period_month?: string | null
          planned_date?: string | null
          priority?: string
          progress_percent?: number
          started_at?: string | null
          status?: string
          submitted_at?: string | null
          tags?: string[]
          task_code?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_id_fkey"
            columns: ["assignee_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_assigner_id_fkey"
            columns: ["assigner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "v_task_summary"
            referencedColumns: ["id"]
          },
        ]
      }
      technical_bom_lines: {
        Row: {
          created_at: string
          id: string
          material_id: string
          note: string | null
          product_id: string
          qty_per_unit: number
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          material_id: string
          note?: string | null
          product_id: string
          qty_per_unit: number
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          material_id?: string
          note?: string | null
          product_id?: string
          qty_per_unit?: number
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "technical_bom_lines_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "technical_bom_lines_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_stock"
            referencedColumns: ["material_id"]
          },
          {
            foreignKeyName: "technical_bom_lines_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "technical_products"
            referencedColumns: ["id"]
          },
        ]
      }
      technical_products: {
        Row: {
          assembly: string | null
          barcode: string | null
          bom_status: string
          bom_url: string | null
          category: string | null
          code: string
          created_at: string
          customer_id: string | null
          customer_item_code: string | null
          description_en: string | null
          drawing_url: string | null
          hs_code: string | null
          id: string
          image_file_id: string | null
          is_active: boolean
          material: string | null
          max_load_kg: number | null
          name: string
          name_de: string | null
          notes: string | null
          origin_country: string | null
          packing: Json
          reference_price: number | null
          set_contents: string | null
          shipping_mark: string | null
          showroom_sample: boolean
          tech_spec: Json
          unit: string
          updated_at: string
        }
        Insert: {
          assembly?: string | null
          barcode?: string | null
          bom_status?: string
          bom_url?: string | null
          category?: string | null
          code: string
          created_at?: string
          customer_id?: string | null
          customer_item_code?: string | null
          description_en?: string | null
          drawing_url?: string | null
          hs_code?: string | null
          id?: string
          image_file_id?: string | null
          is_active?: boolean
          material?: string | null
          max_load_kg?: number | null
          name: string
          name_de?: string | null
          notes?: string | null
          origin_country?: string | null
          packing?: Json
          reference_price?: number | null
          set_contents?: string | null
          shipping_mark?: string | null
          showroom_sample?: boolean
          tech_spec?: Json
          unit?: string
          updated_at?: string
        }
        Update: {
          assembly?: string | null
          barcode?: string | null
          bom_status?: string
          bom_url?: string | null
          category?: string | null
          code?: string
          created_at?: string
          customer_id?: string | null
          customer_item_code?: string | null
          description_en?: string | null
          drawing_url?: string | null
          hs_code?: string | null
          id?: string
          image_file_id?: string | null
          is_active?: boolean
          material?: string | null
          max_load_kg?: number | null
          name?: string
          name_de?: string | null
          notes?: string | null
          origin_country?: string | null
          packing?: Json
          reference_price?: number | null
          set_contents?: string | null
          shipping_mark?: string | null
          showroom_sample?: boolean
          tech_spec?: Json
          unit?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "technical_products_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sales_customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "technical_products_image_file_id_fkey"
            columns: ["image_file_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id"]
          },
        ]
      }
      user_audit_log: {
        Row: {
          action: string
          actor_id: string | null
          after: Json | null
          before: Json | null
          created_at: string
          id: string
          reason: string | null
          target_user_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          id?: string
          reason?: string | null
          target_user_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          id?: string
          reason?: string | null
          target_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_audit_log_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          deleted_at: string | null
          department_id: string | null
          email: string
          employee_code: string | null
          id: string
          is_active: boolean
          last_login_at: string | null
          name: string | null
          password_changed_at: string | null
          password_hash: string
          role: string
          title: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          department_id?: string | null
          email: string
          employee_code?: string | null
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          name?: string | null
          password_changed_at?: string | null
          password_hash: string
          role?: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          deleted_at?: string | null
          department_id?: string | null
          email?: string
          employee_code?: string | null
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          name?: string | null
          password_changed_at?: string | null
          password_hash?: string
          role?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
        ]
      }
      warehouse_docs: {
        Row: {
          code: string
          counterparty: string | null
          created_at: string
          created_by: string | null
          doc_date: string
          id: string
          kind: string
          note: string | null
          reason: string | null
          updated_at: string
        }
        Insert: {
          code: string
          counterparty?: string | null
          created_at?: string
          created_by?: string | null
          doc_date?: string
          id?: string
          kind: string
          note?: string | null
          reason?: string | null
          updated_at?: string
        }
        Update: {
          code?: string
          counterparty?: string | null
          created_at?: string
          created_by?: string | null
          doc_date?: string
          id?: string
          kind?: string
          note?: string | null
          reason?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "warehouse_docs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      warehouse_materials: {
        Row: {
          code: string
          created_at: string
          group_name: string | null
          id: string
          is_active: boolean
          min_stock: number
          name: string
          note: string | null
          shelf_location: string | null
          unit: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          group_name?: string | null
          id?: string
          is_active?: boolean
          min_stock?: number
          name: string
          note?: string | null
          shelf_location?: string | null
          unit?: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          group_name?: string | null
          id?: string
          is_active?: boolean
          min_stock?: number
          name?: string
          note?: string | null
          shelf_location?: string | null
          unit?: string
          updated_at?: string
        }
        Relationships: []
      }
      warehouse_movements: {
        Row: {
          created_at: string
          created_by: string | null
          direction: string
          doc_id: string | null
          id: string
          material_id: string
          note: string | null
          po_line_id: string | null
          production_order_id: string | null
          qc_status: string | null
          qty: number
          qty_rejected: number
          ref_no: string | null
          ref_type: string
          shelf_location: string | null
          transfer_group: string | null
          unit_cost: number | null
          warehouse_id: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          direction: string
          doc_id?: string | null
          id?: string
          material_id: string
          note?: string | null
          po_line_id?: string | null
          production_order_id?: string | null
          qc_status?: string | null
          qty: number
          qty_rejected?: number
          ref_no?: string | null
          ref_type: string
          shelf_location?: string | null
          transfer_group?: string | null
          unit_cost?: number | null
          warehouse_id?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          direction?: string
          doc_id?: string | null
          id?: string
          material_id?: string
          note?: string | null
          po_line_id?: string | null
          production_order_id?: string | null
          qc_status?: string | null
          qty?: number
          qty_rejected?: number
          ref_no?: string | null
          ref_type?: string
          shelf_location?: string | null
          transfer_group?: string | null
          unit_cost?: number | null
          warehouse_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "warehouse_movements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "warehouse_movements_doc_id_fkey"
            columns: ["doc_id"]
            isOneToOne: false
            referencedRelation: "warehouse_docs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "warehouse_movements_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "warehouse_movements_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_stock"
            referencedColumns: ["material_id"]
          },
          {
            foreignKeyName: "warehouse_movements_po_line_id_fkey"
            columns: ["po_line_id"]
            isOneToOne: false
            referencedRelation: "supply_po_line_status"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "warehouse_movements_po_line_id_fkey"
            columns: ["po_line_id"]
            isOneToOne: false
            referencedRelation: "supply_purchase_order_lines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "warehouse_movements_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "production_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "warehouse_movements_production_order_id_fkey"
            columns: ["production_order_id"]
            isOneToOne: false
            referencedRelation: "v_order_tracking"
            referencedColumns: ["production_order_id"]
          },
          {
            foreignKeyName: "warehouse_movements_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      warehouses: {
        Row: {
          address: string | null
          code: string
          created_at: string
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          address?: string | null
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          address?: string | null
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      supply_po_line_status: {
        Row: {
          id: string | null
          material_id: string | null
          note: string | null
          po_id: string | null
          qty_missing: number | null
          qty_ordered: number | null
          qty_received: number | null
          qty_rejected: number | null
          qty2: number | null
          sort_order: number | null
          spec: string | null
          unit_price: number | null
          unit2: string | null
        }
        Relationships: [
          {
            foreignKeyName: "supply_purchase_order_lines_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_materials"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supply_purchase_order_lines_material_id_fkey"
            columns: ["material_id"]
            isOneToOne: false
            referencedRelation: "warehouse_stock"
            referencedColumns: ["material_id"]
          },
          {
            foreignKeyName: "supply_purchase_order_lines_po_id_fkey"
            columns: ["po_id"]
            isOneToOne: false
            referencedRelation: "supply_purchase_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      v_lsx_material_status: {
        Row: {
          material_code: string | null
          material_id: string | null
          material_name: string | null
          production_order_id: string | null
          qty_issued: number | null
          qty_needed: number | null
          qty_remaining: number | null
          unit: string | null
        }
        Relationships: []
      }
      v_order_tracking: {
        Row: {
          code: string | null
          created_at: string | null
          currency: string | null
          current_stage: string | null
          customer_id: string | null
          customer_name: string | null
          customer_po_no: string | null
          due_date: string | null
          id: string | null
          lines_bom_pending: number | null
          lsx_code: string | null
          lsx_status: string | null
          pos_open: number | null
          production_order_id: string | null
          quote_code: string | null
          ship_date: string | null
          status: string | null
          updated_at: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sales_orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "sales_customers"
            referencedColumns: ["id"]
          },
        ]
      }
      v_task_summary: {
        Row: {
          actual_hours: number | null
          assignee_email: string | null
          assignee_id: string | null
          assignee_name: string | null
          assigner_email: string | null
          assigner_id: string | null
          assigner_name: string | null
          cancelled_at: string | null
          category: string | null
          completed_at: string | null
          created_at: string | null
          department_id: string | null
          department_name: string | null
          description: string | null
          due_date: string | null
          estimate_hours: number | null
          id: string | null
          kind: string | null
          parent_id: string | null
          period_month: string | null
          planned_date: string | null
          priority: string | null
          progress_percent: number | null
          started_at: string | null
          status: string | null
          submitted_at: string | null
          tags: string[] | null
          task_code: string | null
          title: string | null
          updated_at: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_id_fkey"
            columns: ["assignee_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_assigner_id_fkey"
            columns: ["assigner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "v_task_summary"
            referencedColumns: ["id"]
          },
        ]
      }
      warehouse_stock: {
        Row: {
          code: string | null
          group_name: string | null
          is_active: boolean | null
          material_id: string | null
          min_stock: number | null
          name: string | null
          on_hand: number | null
          shelf_location: string | null
          unit: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      next_doc_code: { Args: { p_kind: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
