/**
 * Nhãn tiếng Việt cho `changed_fields` của lịch sử phiên bản (0143). Tách file
 * riêng vì trang lịch sử là Server Component còn nhãn thì dùng lại được ở chỗ
 * khác (in ấn, tooltip). Khoá lạ rơi xuống chính tên cột — thà lộ tên kỹ thuật
 * còn hơn giấu mất một thay đổi.
 */
export const FIELD_LABELS: Record<string, string> = {
  parts: 'Bảng định mức',
  code: 'Mã SP',
  name: 'Tên SP',
  name_foreign: 'Tên nước ngoài',
  description_en: 'Mô tả (EN)',
  category: 'Danh mục',
  product_type: 'Loại SP',
  frame_material: 'Vật liệu khung',
  customer_name: 'Khách hàng',
  customer_item_code: 'Mã của khách',
  unit: 'ĐVT',
  material: 'Vật liệu',
  base_material: 'Nhiên liệu (tra tỉ trọng)',
  length_mm: 'Dài (mm)',
  width_mm: 'Rộng (mm)',
  height_mm: 'Cao (mm)',
  length_open_mm: 'Dài mở (mm)',
  width_open_mm: 'Rộng mở (mm)',
  height_open_mm: 'Cao mở (mm)',
  net_weight_kg: 'KL tịnh (kg)',
  frame_weight_kg: 'KL khung (kg)',
  actual_weight_kg: 'KL thực tế (kg)',
  frame_length_m: 'Chiều dài khung (m)',
  paint_area_m2: 'Diện tích sơn (m²)',
  paint_coverage_m2_per_kg: 'Định mức sơn (m²/kg)',
  part_count: 'Số chi tiết',
  max_load_kg: 'Tải trọng (kg)',
  assembly: 'Lắp ráp / tháo rời',
  set_contents: 'Thành phần bộ',
  is_upholstered: 'Có bọc nệm',
  has_glass: 'Có kính',
  is_set: 'Là bộ',
  hs_code: 'Mã HS',
  origin_country: 'Xuất xứ',
  barcode: 'Barcode',
  shipping_mark: 'Shipping mark',
  packing: 'Đóng gói',
  tech_spec: 'Thông số kỹ thuật',
  bom_rev: 'Rev. (biểu mẫu ISO)',
  bom_status: 'Tiến độ BOM',
  bom_file_id: 'File BOM đang dùng',
}
